// Generated by CoffeeScript 1.10.0
'use strict';
var fileUtil, glob;

glob = require('glob');

fileUtil = {
  fetchFileList: function(path, ext, cb) {
    var pattern;
    pattern = path + '/**/*.';
    if (Array.isArray(ext)) {
      pattern += '+(';
      ext.forEach(function(element, index) {
        if (index > 0) {
          pattern += '|';
        }
        pattern += element;
      });
      pattern += ')';
    } else {
      pattern += ext;
    }
    glob(pattern, function(err, matches) {
      if (err) {
        cb(err, null, pattern);
        return;
      }
      cb(null, matches, pattern);
    });
  }
};

module.exports = fileUtil;
